# Generated by Django 5.2.8 on 2025-11-16 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credit_scoring", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_disbursed",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_DISBURSEMENT", "Pending Disbursement"),
                            ("DISBURSED", "Disbursed"),
                            ("ACTIVE", "Active"),
                            ("PAID", "Paid"),
                            ("DEFAULTED", "Defaulted"),
                        ],
                        default="PENDING_DISBURSEMENT",
                        max_length=20,
                    ),
                ),
                ("disbursed_at", models.DateTimeField(null=True)),
                ("due_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="credit_scoring.loanoffer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_method", models.CharField(default="MPESA", max_length=20)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loans.loan"
                    ),
                ),
            ],
        ),
    ]
