# Generated by Django 5.2.8 on 2025-11-16 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "average_weekly_income",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "transaction_consistency",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("has_savings_habit", models.BooleanField(default=False)),
                ("network_diversity", models.IntegerField(default=0)),
                (
                    "fuliza_repayment_ratio",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("last_analysis", models.DateTimeField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_data", models.JSONField()),
                ("analyzed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
