# Generated by Django 5.2.8 on 2025-11-16 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_type', models.CharField(choices=[('C2B', 'Customer to Business'), ('B2C', 'Business to Customer'), ('STK_PUSH', 'STK Push Callback'), ('BALANCE', 'Balance Check')], max_length=20)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('response_sent', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(default=200)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'M-Pesa Webhook Log',
                'verbose_name_plural': 'M-Pesa Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_weekly_income', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('average_weekly_expenses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('transaction_consistency', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('has_savings_habit', models.BooleanField(default=False)),
                ('network_diversity', models.IntegerField(default=0)),
                ('fuliza_repayment_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active_days', models.IntegerField(default=0)),
                ('avg_transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('has_negative_balance', models.BooleanField(default=False)),
                ('late_night_transactions', models.IntegerField(default=0)),
                ('last_analysis', models.DateTimeField(null=True)),
                ('analysis_version', models.CharField(default='v1', max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaPaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_reference', models.CharField(max_length=50)),
                ('transaction_desc', models.CharField(default='Loan Repayment', max_length=100)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_description', models.TextField(blank=True, null=True)),
                ('customer_message', models.TextField(blank=True, null=True)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['checkout_request_id'], name='mpesa_mpesa_checkou_de9a24_idx'), models.Index(fields=['user', 'status'], name='mpesa_mpesa_user_id_cbd1c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('C2B', 'Customer to Business'), ('B2C', 'Business to Customer'), ('C2C', 'Customer to Customer'), ('B2B', 'Business to Business')], max_length=10)),
                ('transaction_category', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('PAYMENT', 'Payment'), ('TRANSFER', 'Transfer'), ('AIRTIME', 'Airtime Purchase'), ('FULIZA', 'Fuliza Credit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('counterparty', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('analyzed', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('transaction_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['mpesa_receipt_number'], name='mpesa_mpesa_mpesa_r_63a7c8_idx'), models.Index(fields=['phone_number', 'transaction_date'], name='mpesa_mpesa_phone_n_5f2b21_idx'), models.Index(fields=['user', 'analyzed'], name='mpesa_mpesa_user_id_801964_idx')],
            },
        ),
    ]
